---
- name: ADD host name to /etc/hosts file
  hosts: all
  remote_user: centos
  become: true
  become_method: sudo
  become_user: root

  tasks:
 # - name: install ntp in all hosts
 #   yum: name=ntp state=latest
 # - name: write ntp config file
 #   template: src=/home/centos/initial-files/ntp.conf dest=/etc/ntp.conf
#  - name: change file permission
#    file: path=/etc/ntp.conf owner=root group=root mode=0600
#    notify:
#    - restart ntp

   - name: ADD host name to /etc/hosts file
     blockinfile:
             dest: /etc/hosts
             block: |
                   172.20.0.175 web.novopay.in
                   172.20.0.112 jump.novopay.in
                   
                   172.20.7.132 webapp01.novopay.in
                   172.20.8.10  webapp02.novopay.in
                   
                   172.20.2.76  services01.novopay.in
                   172.20.3.10  services02.novopay.in
                   
                   172.20.2.160 wallet01.novopay.in
                   172.20.3.77  wallet02.novopay.in
                   
                   172.20.2.28  portal.novopay.in
                   172.20.2.126 sales.novopay.in
                   172.20.2.22  utility.novopay.in
                   172.20.2.224 rbl-sftp.novopay.in
                   172.20.2.194 mydbops-nagios.novopay.in
                   172.20.2.39  nagios.novopay.in
                   
                   172.20.4.231 db01.novopay.in
                   172.20.4.232 db02.novopay.in
                   172.20.5.203 db03.novopay.in
                   
                   172.20.6.246 es01.novopay.in
                   172.20.6.247 es02.novopay.in
                   172.20.6.248 es03.novopay.in
                   
                   192.168.111.9 rblfwd-remittance.novopay.in
                   192.168.111.9 airtel-fwd.novopay.in
#     notify:
#     - restart network



#  - name: copy banner file
#    template: src=/home/centos/initial-files/banner dest=/etc/ssh/banner
#  - name: copy grub file
#    template: src=/home/centos/initial-files/grub dest=/etc/default/grub
#  - name: change file permission for grub
#    file: path=/etc/ntp.conf owner=root group=root mode=0600
#
#  - name: copy sshd config file
#    template: src=/home/centos/initial-files/sshd_config dest=/etc/default/grub
#  - name: change file permission for grub
#    file: path=/etc/default/grub owner=root group=root mode=0600

        

  handlers:
  - name: restart network
    service: name=network state=restarted
