---
- name: Copy nrpe in all hosts
  hosts: all
  remote_user: centos
  become: true
  become_method: sudo
  become_user: root

  tasks:
  - name: Copy nrpe in all hosts
    synchronize:
        src : /tmp/check_mem 
        dest: /usr/local/nagios/libexec/
    notify:
     - restart nrpe

  handlers:
  - name: restart nrpe
    service: name=nrpe state=restarted
