---
- name: Install packege in all hosts
  hosts: clamav 
  remote_user: centos
  become: true
  become_method: sudo
  become_user: root

  tasks:
 # - name: install ntp in all hosts
 #   yum: name=ntp state=latest
 # - name: write ntp config file
 #   template: src=/home/centos/initial-files/ntp.conf dest=/etc/ntp.conf
#  - name: change file permission
#    file: path=/etc/ntp.conf owner=root group=root mode=0600
#    notify:
#    - restart ntp

  - name: "Install Common Libraries from CentOS mirror"
    yum: state=present name={{ item }}
    with_items:
    - epel-release  
    - clamav-server 
    - clamav-data 
    - clamav-update 
    - clamav-filesystem 
    - clamav 
    - clamav-scanner-systemd 
    - clamav-devel 
    - clamav-lib 
    - clamav-server-systemd



#  - name: copy banner file
#    template: src=/home/centos/initial-files/banner dest=/etc/ssh/banner
#  - name: copy grub file
#    template: src=/home/centos/initial-files/grub dest=/etc/default/grub
#  - name: change file permission for grub
#    file: path=/etc/ntp.conf owner=root group=root mode=0600
#
#  - name: copy sshd config file
#    template: src=/home/centos/initial-files/sshd_config dest=/etc/default/grub
#  - name: change file permission for grub
#    file: path=/etc/default/grub owner=root group=root mode=0600
